### ISSUE TITLE
Support obfuscation of output code

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#1094]
This is a catch-all issue for work related to allowing Slang to produce output (both serialized IR and final DXIL/SPIR-V) that exposes as little of the original names used in the source program as possible.

- [x] Don't emit HLSL/GLSL names using the IR hints when `-obfuscate` is specified (#1075)
- [x] Strip name-hint decorations in front-end when `-obfuscate` is specified (#1092)
- [x] Make sure that emit logic doesn't depend on mangled symbol names in order to compute names for builtin function (#1096)
- [ ] Use hashes for mangled symbol export/import names when `-obfuscate` is specified

**Comment by csyonghe** [comment]
This is considered implemented, closing the issue now.
