### ISSUE TITLE
Scope reduction: eliminate superfluous input/output paths

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#384]
The compiler codebase is starting to get unwieldy based on the number of different options for input and output that we support. For posterity, here are the different ways that Slang currently has to handle compilation and code generation:

- **"Pass-through" mode**: HLSL/GLSL input, `-no-checking`, no `import`s. Just scrape reflection information, add layouts where they are missing, and emit the code again as written. Don't even touch function bodies (just store them as a sequence of tokens).

- **AST-to-AST "partial rewrite mode**: HLSL/GLSL input, `-no-checking`, one or more `import`s. Fully parse and check users code, but suppress any error messages. Determine what Slang modules they use (and fully check those), run AST-to-AST legalization on everything (plus cross-compilation on just the Slang code), and then emit from the resulting Slang and user ASTs.

- **AST-to-AST "full rewrite" mode**: HLSL/Slang input, checking enabled. Fully parse and check all code (user and imported), and actually emit error messages. Pass everything through AST-to-AST cross-compilation and legalization, and then emit the resulting ASTs.

- **"partial" IR mode**: HLSL/GLSL input, `-no-checking`, `-use-ir`, one or more `import`s. Similar to "partial rewrite mode" but Slang code is translated to IR and legalized there, so that the final output step needs to merge together the user's code in an AST with the library code in the IR.

- **full IR mode**: HLSL/Slang input, checking enabled, `-use-ir`. Everything gets parsed, checked, and translated to IR uniformly. Everything gets legalized in IR. Everything gets emitted from IR.

The goal is to drop everything but the last one of those modes, so that we can focus on effort on making that one mode as good as possible.

This work will probably involve improvements to the IR code generation path, but for now we just want to capture the stuff we can drop (in a good order for doing the dropping):

- [x] #380: Remove `#import` support (not related, but a simple removal we need anyway)
- [x] #383: Remove the notion of a "pass-through" mode
- [x] #382: Remove support for GLSL input
- [x] #381: Remove support for the `-no-checking` flag
- [x] #218: Make IR codegen the default (and only) path

**Comment by tfoleyNV** [comment]
All of the sub-items are implemented in a first-pass capacity, so I'm going to close this issue. There are still lots of loose threads, though, so the sub-items won't be closed right away.
